In [ ]:
import numpy as np

# ---------------- FUZZY SETS ----------------
# Define three fuzzy sets
A = np.array([0.2, 0.5, 0.7])
B = np.array([0.3, 0.6, 0.4])
C = np.array([0.9, 0.1, 0.8])

print("Fuzzy Set A:", A)
print("Fuzzy Set B:", B)
print("Fuzzy Set C:", C)

# ---------------- BASIC OPERATIONS ----------------

# Union (A ∪ B)
union_AB = np.maximum(A, B)

# Intersection (A ∩ B)
intersection_AB = np.minimum(A, B)

# Complement of A
complement_A = 1 - A

# Difference (A - B)
difference_AB = np.minimum(A, 1 - B)

print("\nUnion (A ∪ B):", union_AB)
print("Intersection (A ∩ B):", intersection_AB)
print("Complement of A:", complement_A)
print("Difference (A - B):", difference_AB)

# ---------------- FUZZY RELATIONS ----------------

# Relation R = A x B
R = np.minimum.outer(A, B)

# Relation S = B x C
S = np.minimum.outer(B, C)

print("\nFuzzy Relation R (A x B):\n", R)
print("\nFuzzy Relation S (B x C):\n", S)

# ---------------- MAX-MIN COMPOSITION ----------------

# Initialize result matrix
composition = np.zeros((len(A), len(C)))

# Max-Min Composition: R o S
for i in range(len(A)):
    for j in range(len(C)):
        composition[i][j] = max(
            min(R[i][k], S[k][j]) for k in range(len(B))
        )

print("\nMax-Min Composition (R o S):\n", composition)

Fuzzy Set A: [0.2 0.5 0.7]
Fuzzy Set B: [0.3 0.6 0.4]
Fuzzy Set C: [0.9 0.1 0.8]

Union (A ∪ B): [0.3 0.6 0.7]
Intersection (A ∩ B): [0.2 0.5 0.4]
Complement of A: [0.8 0.5 0.3]
Difference (A - B): [0.2 0.4 0.6]

Fuzzy Relation R (A x B):
 [[0.2 0.2 0.2]
 [0.3 0.5 0.4]
 [0.3 0.6 0.4]]

Fuzzy Relation S (B x C):
 [[0.3 0.1 0.3]
 [0.6 0.1 0.6]
 [0.4 0.1 0.4]]

Max-Min Composition (R o S):
 [[0.2 0.1 0.2]
 [0.5 0.1 0.5]
 [0.6 0.1 0.6]]
